# Prepare TFRecords
#python preprocessing_unlabeled.py --infile Data/road/csv_individual/ambient_dyno_drive_winter.csv --outfile Data/road/TFRecords_individual/TFRecord_dyno_drive_winter_signals202 --exclude_constant_signals --constant_signal_file Data/road/constant_signals.json --min_max_file Data/road/ranges/individual/min_max_merge.json
python preprocessing_unlabeled.py --infile Data/road/csv_individual/ambient_dyno_drive_basic_short.csv --outfile Data/road/TFRecords_individual/TFRecord_dyno_drive_basic_short_signals202 --exclude_constant_signals --constant_signal_file Data/road/constant_signals.json --min_max_file Data/road/ranges/individual/min_max_merge.json
python preprocessing_unlabeled.py --infile Data/road/csv_individual/ambient_dyno_drive_basic_long.csv --outfile Data/road/TFRecords_individual/TFRecord_dyno_drive_basic_long_signals202 --exclude_constant_signals --constant_signal_file Data/road/constant_signals.json --min_max_file Data/road/ranges/individual/min_max_merge.json
#python preprocessing_unlabeled.py --infile Data/road/csv_individual/ambient_dyno_drive_benign_anomaly.csv --outfile Data/road/TFRecords_individual/TFRecord_dyno_drive_benign_anomaly_signals202 --exclude_constant_signals --constant_signal_file Data/road/constant_signals.json --min_max_file Data/road/ranges/individual/min_max_merge.json
python preprocessing_unlabeled.py --infile Data/road/csv_individual/ambient_dyno_drive_extended_long.csv --outfile Data/road/TFRecords_individual/TFRecord_dyno_drive_extended_long_signals202 --exclude_constant_signals --constant_signal_file Data/road/constant_signals.json --min_max_file Data/road/ranges/individual/min_max_merge.json
python preprocessing_unlabeled.py --infile Data/road/csv_individual/ambient_dyno_drive_extended_short.csv --outfile Data/road/TFRecords_individual/TFRecord_dyno_drive_extended_short_signals202 --exclude_constant_signals --constant_signal_file Data/road/constant_signals.json --min_max_file Data/road/ranges/individual/min_max_merge.json
python preprocessing_unlabeled.py --infile Data/road/csv_individual/ambient_dyno_drive_radio_infotainment.csv --outfile Data/road/TFRecords_individual/TFRecord_dyno_drive_radio_infotainment_signals202 --exclude_constant_signals --constant_signal_file Data/road/constant_signals.json --min_max_file Data/road/ranges/individual/min_max_merge.json
#python preprocessing_unlabeled.py --infile Data/road/csv_individual/ambient_dyno_exercise_all_bits.csv --outfile Data/road/TFRecords_individual/TFRecord_dyno_exercise_all_bits_signals202 --exclude_constant_signals --constant_signal_file Data/road/constant_signals.json --min_max_file Data/road/ranges/without_street/min_max_merge.json
#python preprocessing_unlabeled.py --infile Data/road/csv_individual/ambient_dyno_idle_radio_infotainment.csv --outfile Data/road/TFRecords_individual/TFRecord_dyno_idle_radio_infotainment_signals202 --exclude_constant_signals --constant_signal_file Data/road/constant_signals.json --min_max_file Data/road/ranges/individual/min_max_merge.json
#python preprocessing_unlabeled.py --infile Data/road/csv_individual/ambient_dyno_reverse.csv --outfile Data/road/TFRecords_individual/TFRecord_dyno_reverse_signals202 --exclude_constant_signals --constant_signal_file Data/road/constant_signals.json --min_max_file Data/road/ranges/individual/min_max_merge.json
#python preprocessing_unlabeled.py --infile Data/road/csv_individual/ambient_highway_street_driving_diagnostics.csv --outfile Data/road/TFRecords_individual/ambient_highway_street_driving_diagnostics_signals202 --exclude_constant_signals --constant_signal_file Data/road/constant_signals.json --min_max_file Data/road/ranges/individual/min_max_merge.json

# Apply Datasplit
python apply_windowing.py --infile Data/road/TFRecords_individual/TFRecord_dyno_drive_basic_long_signals202.tfrecords --outpath Data/road/datasplit/individual/train/ --window 150 --signals 202
python apply_windowing.py --infile Data/road/TFRecords_individual/TFRecord_dyno_drive_extended_long_signals202.tfrecords --outpath Data/road/datasplit/individual/train/ --window 150 --signals 202
python apply_windowing.py --infile Data/road/TFRecords_individual/TFRecord_dyno_drive_extended_short_signals202.tfrecords --outpath Data/road/datasplit/individual/train/ --window 150 --signals 202
python apply_windowing.py --infile Data/road/TFRecords_individual/TFRecord_dyno_drive_basic_short_signals202.tfrecords --outpath Data/road/datasplit/individual/val/ --window 150 --signals 202
python apply_windowing.py --infile Data/road/TFRecords_individual/TFRecord_dyno_drive_radio_infotainment_signals202.tfrecords --outpath Data/road/datasplit/individual/test/ --window 150 --signals 202