#python preprocessing_labeled.py --infile Data/csv_attack/correlated_signal_attack_1_masquerade.csv --outfile Data/TFRecords_attack/TFRecord_correlated_signal_attack_1_masquerade_window150_signals202 --windowsize 150 --exclude_constant_signals --constant_signal_file Data/constant_signals.json
#python preprocessing_labeled.py --infile Data/csv_attack/correlated_signal_attack_2_masquerade.csv --outfile Data/TFRecords_attack/TFRecord_correlated_signal_attack_2_masquerade_window150_signals202 --windowsize 150 --exclude_constant_signals --constant_signal_file Data/constant_signals.json
#python preprocessing_labeled.py --infile Data/csv_attack/correlated_signal_attack_3_masquerade.csv --outfile Data/TFRecords_attack/TFRecord_correlated_signal_attack_3_masquerade_window150_signals202 --windowsize 150 --exclude_constant_signals --constant_signal_file Data/constant_signals.json
#python preprocessing_labeled.py --infile Data/csv_attack/max_engine_coolant_temp_attack_masquerade.csv --outfile Data/TFRecords_attack/TFRecord_max_engine_coolant_temp_attack_masquerade_window150_signals202 --windowsize 150 --exclude_constant_signals --constant_signal_file Data/constant_signals.json
#python preprocessing_labeled.py --infile Data/csv_attack/max_speedometer_attack_1_masquerade.csv --outfile Data/TFRecords_attack/TFRecord_max_speedometer_attack_1_masquerade_window150_signals202 --windowsize 150 --exclude_constant_signals --constant_signal_file Data/constant_signals.json
#python preprocessing_labeled.py --infile Data/csv_attack/max_speedometer_attack_2_masquerade.csv --outfile Data/TFRecords_attack/TFRecord_max_speedometer_attack_2_masquerade_window150_signals202 --windowsize 150 --exclude_constant_signals --constant_signal_file Data/constant_signals.json
#python preprocessing_labeled.py --infile Data/csv_attack/max_speedometer_attack_3_masquerade.csv --outfile Data/TFRecords_attack/TFRecord_max_speedometer_attack_3_masquerade_window150_signals202 --windowsize 150 --exclude_constant_signals --constant_signal_file Data/constant_signals.json
#python preprocessing_labeled.py --infile Data/csv_attack/reverse_light_off_attack_1_masquerade.csv --outfile Data/TFRecords_attack/TFRecord_reverse_light_off_attack_1_masquerade_window150_signals202 --windowsize 150 --exclude_constant_signals --constant_signal_file Data/constant_signals.json
#python preprocessing_labeled.py --infile Data/csv_attack/reverse_light_off_attack_2_masquerade.csv --outfile Data/TFRecords_attack/TFRecord_reverse_light_off_attack_2_masquerade_window150_signals202 --windowsize 150 --exclude_constant_signals --constant_signal_file Data/constant_signals.json
#python preprocessing_labeled.py --infile Data/csv_attack/reverse_light_off_attack_3_masquerade.csv --outfile Data/TFRecords_attack/TFRecord_reverse_light_off_attack_3_masquerade_window150_signals202 --windowsize 150 --exclude_constant_signals --constant_signal_file Data/constant_signals.json
#python preprocessing_labeled.py --infile Data/csv_attack/reverse_light_on_attack_1_masquerade.csv --outfile Data/TFRecords_attack/TFRecord_reverse_light_on_attack_1_masquerade_window150_signals202 --windowsize 150 --exclude_constant_signals --constant_signal_file Data/constant_signals.json
#python preprocessing_labeled.py --infile Data/csv_attack/reverse_light_on_attack_2_masquerade.csv --outfile Data/TFRecords_attack/TFRecord_reverse_light_on_attack_2_masquerade_window150_signals202 --windowsize 150 --exclude_constant_signals --constant_signal_file Data/constant_signals.json
#python preprocessing_labeled.py --infile Data/csv_attack/reverse_light_on_attack_3_masquerade.csv --outfile Data/TFRecords_attack/TFRecord_reverse_light_on_attack_3_masquerade_window150_signals202 --windowsize 150 --exclude_constant_signals --constant_signal_file Data/constant_signals.json
python preprocessing_labeled.py --infile Data/road/csv_attack/suspension_attack_1.csv --outfile Data/road/TFRecords_attack/TFRecord_suspension_attack_1_window150_signals202 --windowsize 150 --exclude_constant_signals --constant_signal_file Data/road/constant_signals.json --min_max_file Data/road/ranges/min_max_merge.json
python preprocessing_labeled.py --infile Data/road/csv_attack/suspension_attack_001.csv --outfile Data/road/TFRecords_attack/TFRecord_suspension_attack_001_window150_signals202 --windowsize 150 --exclude_constant_signals --constant_signal_file Data/road/constant_signals.json --min_max_file Data/road/ranges/min_max_merge.json
python preprocessing_labeled.py --infile Data/road/csv_attack/suspension_attack_01.csv --outfile Data/road/TFRecords_attack/TFRecord_suspension_attack_01_window150_signals202 --windowsize 150 --exclude_constant_signals --constant_signal_file Data/road/constant_signals.json --min_max_file Data/road/ranges/min_max_merge.json